version: '3.9'

services:
  postgres-db:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pettersonapps-db
    volumes:
      - pettersonapps-db:/var/lib/postgresql/pettersonapps-db

volumes:
  pettersonapps-db: